server:
  port: 8080

keystore:
  store: gradebook.jks
  storepass: storepassword
  keyalias: gradebook

spring:
  jersey:
    application-path: /api/v1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/gradebook?useSSL=false
    username: user
    password: password