server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/gradebook
    username: user
    password: password