server:
  port: 8081

resource:
  id: gradebook

security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:8080/oauth/token_key

spring:
  jersey:
    application-path: /api/v1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        globally_quoted_identifiers: false
        show_sql: false
        format_sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/gradebook?useSSL=false
    username: user
    password: password